const articles = [
  {
    label: "1010",
    date: "10.7.2025",
    title: "Potes & Bots",
    subtitle: "Histoire d'amour numérique",
    mention: "Récit",
    image: "0001-1.jpg",
    text: "Vous souvenez-vous de vos premiers pas sur Internet ? Beaucoup d’entre nous ont grandi à une époque où les téléphones avaient des touches, où les SMS étaient limités à 200 caractères, et où ouvrir un Skyblog ou bidouiller du HTML se faisait sans trop y penser. À cette époque, chaque hobby avait son forum, et on était sûrs que chaque mot publié sur le web venait d’une vraie personne, quelque part.<br><br>Puis, tout a changé avec l’arrivée des réseaux sociaux. Facebook, le premier. Certains ont collectionné les « amis » bien avant tout le monde, pendant que d’autres, ont mis du temps à s’y faire. Et alors qu’on commençait à apprivoiser ce nouvel espace, Instagram a débarqué, puis TikTok, et la course ne s’est jamais vraiment arrêtée.",
    image2: "0001-2.jpg",
    text2:"Aujourd’hui, en 2025, nous jonglons tous avec une multitude de plateformes. WhatsApp pour les amis et les collègues, avec un compte pro, un compte perso, Facebook pour la famille ou les évènements, Instagram pour les rencontres ou les projets, TikTok pour les plus téméraires… Sans oublier les irréductibles du SMS ou ceux qui préfèrent encore décrocher leur téléphone pour un appel. Cette surabondance de canaux nous pousse à nous comporter, parfois, comme de véritables « bots » : il faut donner des nouvelles, montrer qu’on existe, partager, publier, commenter. Les rencontres spontanées se font rares ; il est devenu difficile de commencer une conversation sans raison, tant nous sommes informés sur tout et sur tous.",
    image3: "0001-3.jpg",
    text3:"On a souvent entendu que notre génération était « égocentrée », la fameuse « me me me generation » dont parlait le Times en 2013. Mais au fond, est-ce vraiment le cas ? Derrière les selfies et les stories, c’est surtout une envie de connexion qui s’exprime. Notre époque a mis en avant l’empathie, la communication non-violente, le respect de l’autre .",
    image4: "0001-4.jpg",
    text4:"On peut être nostalgique d’une époque où tout semblait plus simple, avec moins de plateformes. Mais cette diversité de formats et de modes d’expression a aussi ses avantages. Certains préfèrent les vocaux, d’autres les longues discussions écrites, d’autres encore les stories ou les appels improvisés. Chacun trouve sa façon de communiquer, de tisser des liens, de partager ses passions.",
    image5: "",
    text5:"Au final, si l’on accepte de vivre dans un monde dématérialisé, force est de constater que jamais il n’a été aussi facile de rencontrer des personnes qui nous ressemblent, de se regrouper autour de centres d’intérêt communs, de s’ouvrir à de nouvelles communautés. Oui, il y a moins de place pour le hasard, mais il y a aussi plus d’opportunités pour l’échange.",
    image6: "",
    text6:"",
    id: "0001",
  },
  {
    label: "Sonore",
    date: "10.7.2025",
    title: "Guitare du XXIIème siècle",
    subtitle: "Trans-Humanisme Musical",
    mention: "Dossier Technique",
    image: "0002-1.jpg",
    text: "On ne fait pas beaucoup plus organique que le son d'une guitare. Son imperfection, ses vibratos, tout ça évoque facilement la voix humaine. Et à côté de ça, on trouve la mécanique impossible des D.A.W. La techno allemande, aux sonorités industrielles.<br>La nostalgie est un réflexe assez naturel, et chez les guitaristes, souvent elle prend forme avec des idées comme \"tu vois, dans les années 70', ils faisaient tout en une seule take, bam ! C'est pour ça que c'est des chefs d'oeuvre !\" ** il tire une latte sur sa roulée mal fagotée **<br>Non pas que je n'apprécie pas les années 70 et leurs sonorités, loin de là, mais il faut quand même admettre que à leur époque, ils étaient bien au summum de la modernité technologique. Ils ont été les premiers à torturer le son avec des amplis et des effets carrément novateurs. S'ils étaient de la partie aujourd'hui, c'est certain qu'ils seraient les premiers à s'amuser avec les logiciels actuels, ils ne seraient pas dans un garage à jouer une Les Paul dans un Fender twin à fond de Fuzz.",
    image2: "",
    text2: "On ne fait pas beaucoup plus organique que le son d'une guitare. Son imperfection, ses vibratos, tout ça évoque facilement la voix humaine. Et à côté de ça, on trouve la mécanique impossible des D.A.W. La techno allemande, aux sonorités industrielles.<br>La nostalgie est un réflexe assez naturel, et chez les guitaristes, souvent elle prend forme avec des idées comme \"tu vois, dans les années 70', ils faisaient tout en une seule take, bam ! C'est pour ça que c'est des chefs d'oeuvre !\" ** il tire une latte sur sa roulée mal fagotée **<br>Non pas que je n'apprécie pas les années 70 et leurs sonorités, loin de là, mais il faut quand même admettre que à leur époque, ils étaient bien au summum de la modernité technologique. Ils ont été les premiers à torturer le son avec des amplis et des effets carrément novateurs. S'ils étaient de la partie aujourd'hui, c'est certain qu'ils seraient les premiers à s'amuser avec les logiciels actuels, ils ne seraient pas dans un garage à jouer une Les Paul dans un Fender twin à fond de Fuzz.",
    image3: "",
    text3:"",
    image4: "",
    text4:"",
    image5: "",
    text5:"",
    image6: "",
    text6:"",
    id: "0002",
  },
  {
    label: "D.I.Y",
    date: "10.7.2025",
    title: "L'âge d'or de la créativité individuelle",
    subtitle: "Une histoire de makers",
    mention: "Observations",
    image: "0003-01.jpg",
    text: "L'accès à la technologie moderne étant ce qu'il est, canaliser les ambitions démesurées des touche-à-tout du garage n'est plus à l'ordre du jour. Y'a t-il un monde après la production de masse ?",
    image2: "",
    text2:"Difficile de faire plus organique qu'une guitare, son vibrato, son imperfection, elle est comme une voix humaine. Et à côté d'elle, se trouve l'implacable robotique des DAW. Une danse improbable s'improvise, non sans structure.",
    image3: "",
    text3:"",
    image4: "",
    text4:"",
    image5: "",
    text5:"",
    image6: "",
    text6:"",
    id: "0003",
  }
];

module.exports = articles;